// ================= ORGANISMOS =================

const serviciosSalud = [
  "Servicio de Salud Arica",
  "Servicio de Salud Iquique",
  "Servicio de Salud Antofagasta",
  "Servicio de Salud Atacama",
  "Servicio de Salud Coquimbo",
  "Servicio de Salud Valparaíso - San Antonio",
  "Servicio de Salud Viña del Mar - Quillota",
  "Servicio de Salud Aconcagua",
  "Servicio de Salud Metropolitano Norte",
  "Servicio de Salud Metropolitano Occidente",
  "Servicio de Salud Metropolitano Central",
  "Servicio de Salud Metropolitano Oriente",
  "Servicio de Salud Metropolitano Sur",
  "Servicio de Salud Metropolitano Sur Oriente",
  "Servicio de Salud O’Higgins",
  "Servicio de Salud Maule",
  "Servicio de Salud Ñuble",
  "Servicio de Salud Concepción",
  "Servicio de Salud Talcahuano",
  "Servicio de Salud Biobío",
  "Servicio de Salud Arauco",
  "Servicio de Salud Araucanía Norte",
  "Servicio de Salud Araucanía Sur",
  "Servicio de Salud Valdivia",
  "Servicio de Salud Osorno",
  "Servicio de Salud Reloncaví",
  "Servicio de Salud Chiloé",
  "Servicio de Salud Aysén",
  "Servicio de Salud Magallanes"
];

const seremisSalud = [
  "SEREMI de Salud Región de Arica y Parinacota",
  "SEREMI de Salud Región de Tarapacá",
  "SEREMI de Salud Región de Antofagasta",
  "SEREMI de Salud Región de Atacama",
  "SEREMI de Salud Región de Coquimbo",
  "SEREMI de Salud Región de Valparaíso",
  "SEREMI de Salud Región Metropolitana",
  "SEREMI de Salud Región de O’Higgins",
  "SEREMI de Salud Región del Maule",
  "SEREMI de Salud Región de Ñuble",
  "SEREMI de Salud Región del Biobío",
  "SEREMI de Salud Región de La Araucanía",
  "SEREMI de Salud Región de Los Ríos",
  "SEREMI de Salud Región de Los Lagos",
  "SEREMI de Salud Región de Aysén",
  "SEREMI de Salud Región de Magallanes"
];

const organismoRegionMap = {

  "Servicio de Salud Arica": "Arica y Parinacota",
  "Servicio de Salud Iquique": "Tarapacá",
  "Servicio de Salud Antofagasta": "Antofagasta",
  "Servicio de Salud Atacama": "Atacama",
  "Servicio de Salud Coquimbo": "Coquimbo",
  "Servicio de Salud Valparaíso - San Antonio": "Valparaíso",
  "Servicio de Salud Viña del Mar - Quillota": "Valparaíso",
  "Servicio de Salud Aconcagua": "Valparaíso",
  "Servicio de Salud Metropolitano Norte": "Metropolitana de Santiago",
  "Servicio de Salud Metropolitano Occidente": "Metropolitana de Santiago",
  "Servicio de Salud Metropolitano Central": "Metropolitana de Santiago",
  "Servicio de Salud Metropolitano Oriente": "Metropolitana de Santiago",
  "Servicio de Salud Metropolitano Sur": "Metropolitana de Santiago",
  "Servicio de Salud Metropolitano Sur Oriente": "Metropolitana de Santiago",
  "Servicio de Salud O’Higgins": "O’Higgins",
  "Servicio de Salud Maule": "Maule",
  "Servicio de Salud Ñuble": "Ñuble",
  "Servicio de Salud Concepción": "Biobío",
  "Servicio de Salud Talcahuano": "Biobío",
  "Servicio de Salud Biobío": "Biobío",
  "Servicio de Salud Arauco": "Biobío",
  "Servicio de Salud Araucanía Norte": "La Araucanía",
  "Servicio de Salud Araucanía Sur": "La Araucanía",
  "Servicio de Salud Valdivia": "Los Ríos",
  "Servicio de Salud Osorno": "Los Lagos",
  "Servicio de Salud Reloncaví": "Los Lagos",
  "Servicio de Salud Chiloé": "Los Lagos",
  "Servicio de Salud Aysén": "Aysén",
  "Servicio de Salud Magallanes": "Magallanes y la Antártica Chilena",

  "SEREMI de Salud Región de Arica y Parinacota": "Arica y Parinacota",
  "SEREMI de Salud Región de Tarapacá": "Tarapacá",
  "SEREMI de Salud Región de Antofagasta": "Antofagasta",
  "SEREMI de Salud Región de Atacama": "Atacama",
  "SEREMI de Salud Región de Coquimbo": "Coquimbo",
  "SEREMI de Salud Región de Valparaíso": "Valparaíso",
  "SEREMI de Salud Región Metropolitana": "Metropolitana de Santiago",
  "SEREMI de Salud Región de O’Higgins": "O’Higgins",
  "SEREMI de Salud Región del Maule": "Maule",
  "SEREMI de Salud Región de Ñuble": "Ñuble",
  "SEREMI de Salud Región del Biobío": "Biobío",
  "SEREMI de Salud Región de La Araucanía": "La Araucanía",
  "SEREMI de Salud Región de Los Ríos": "Los Ríos",
  "SEREMI de Salud Región de Los Lagos": "Los Lagos",
  "SEREMI de Salud Región de Aysén": "Aysén",
  "SEREMI de Salud Región de Magallanes": "Magallanes y la Antártica Chilena"
};